version: "3.8"
networks:
  minitron:
    driver: bridge
services:
  api:
    build:
      context: ./minitronapi # Path to your API's Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5248:80" # Expose API on port 5000 of the host
    networks:
      - minitron

  frontend:
    build:
      context: ./minitronweb # Path to your frontend's Dockerfile
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:80"
    env_file:
      - .env
    restart: always
    networks:
      - minitron
      # Expose frontend on port 3000 of the host
volumes:
  minitron_postgres_data:
