version: "3.8"
networks:
  minitron-max:
    driver: bridge
services:
  api-max:
    build:
      context: ./minitronapi
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5249
    ports:
      - "5249:5249" # Map host port 5249 to container port 5249
    volumes:
      - ./minitronapi:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    networks:
      - minitron-max

  frontend-max:
    build:
      context: ./minitronweb
      dockerfile: Dockerfile
    depends_on:
      - api-max
    ports:
      - "3001:3000" # Map host port 3001 to container port 3000
    volumes:
      - ./minitronweb:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - minitron-max
