# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Remove the default nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the custom configuration file from the host machine to the container
COPY timdev.conf /etc/nginx/conf.d/

# Optionally expose port 80 if you plan to run this container directly
EXPOSE 80

# Start Nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]
